In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('iris-data.csv')
df.head()

Sepal Length  Sepal Width  Petal Length  Petal Width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
df = df[['Sepal Length', 'Sepal Width']]
df.head()

Sepal Length  Sepal Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6

In [4]:
eigenvectors, eigenvalues, _ = np.linalg.svd(df.values, full_matrices=False)

In [5]:
eigenvalues

array([81.25483015,  6.96796793])

In [6]:
eigenvalues = np.cumsum(eigenvalues)
eigenvalues

array([81.25483015, 88.22279808])

In [7]:
eigenvalues /= eigenvalues.max()
eigenvalues

array([0.92101851, 1.        ])

In [8]:
eigenvectors

array([[-0.07553027, -0.11068158],
       [-0.07052087, -0.06007995],
       [-0.06946245, -0.09874988],
       [-0.06780439, -0.09257869],
       [-0.07500106, -0.13001654],
       [-0.08106887, -0.14194824],
       [-0.06949767, -0.13083793],
       [-0.07387221, -0.10451038],
       [-0.06448827, -0.0802363 ],
       [-0.07108529, -0.07283303],
       [-0.07994002, -0.11644208],
       [-0.07168494, -0.11767416],
       [-0.06942723, -0.06666184],
       [-0.06395906, -0.09957127],
       [-0.08600784, -0.12837377],
       [-0.08717191, -0.18596798],
       [-0.08106887, -0.14194824],
       [-0.07553027, -0.11068158],
       [-0.08378535, -0.1094495 ],
       [-0.07722355, -0.14894082],
       [-0.07824674, -0.07818284],
       [-0.07665912, -0.13618774],
       [-0.07062652, -0.15634409],
       [-0.07440141, -0.08517542],
       [-0.07168494, -0.11767416],
       [-0.0716145 , -0.05349806],
       [-0.07387221, -0.10451038],
       [-0.0766239 , -0.10409969],
       [-0.07605947,

In [9]:
eigenvectors.shape

(150, 2)

In [10]:
P = eigenvectors[0]
P

array([-0.07553027, -0.11068158])